In [9]:
from math import factorial, radians

def sen(x: int, n: int = 1000) -> float:
    """
    Esta función calcula la suma de una serie con un patrón específico.

    Parámetros:
    x (float): El número que se utilizará en la serie, sen(x).
    n (int): El número de términos en la serie. Por defecto es 1000.

    Devuelve:
    float: El resultado de la suma de la serie.
    """
    resultado = 0.0  # Inicializa el resultado en 0.0
    # x = radians(x)  # Convierte el valor de x a radianes
    for i in range(n):  # Itera sobre cada número en el rango hasta n
        # Añade el siguiente término de la serie al resultado
        resultado += (-1)**i * x**(2*i+1) / factorial(2*i+1)
    return resultado  # Devuelve el resultado

sen(1)

0.8414709848078965

Inversa de una matriz por eliminación gaussiana

In [10]:
import numpy as np
def row_lamb(i, lamb, A):
    M = np.copy(A)
    M[[i]] *= lamb
    return M

def row_comb(i, j, lamb, A):
    M = np.copy(A)
    M[[i]] += lamb * M[[j]]
    return M

def row_swap(i, j, A):
    M = np.copy(A)
    M[[i, j]] = M[[j, i]]
    return M

#Gaussian Elimination
def inverse_Gaussian_Elimination( A0 ):
    #Making local copy of matrix
    A = 1.0*np.copy(A0) # Normalizaciobn
    n = len(A)

    A = np.hstack((A, np.identity(n)))
    #Sweeping all the columns in order to eliminate coefficients of the i-th variable
    for i in range( 0, n ):

        #Sweeping all the rows for the i-th column in order to find the first non-zero coefficient
        for j in range( i, n ):
            if A[i,j] != 0:
                #Normalization coefficient
                Norm = A[i,j]
                break

        #Applying swap operation to put the non-zero coefficient in the i-th row
        A = row_swap( i, j, A )

        #Eliminating the coefficient associated to the i-th variable
        for j in range( n ):
            if i != j:
                lamb = -A[j,i]/Norm
                A = row_comb( j, i, lamb , A )

    for i in range(n):
        A = row_lamb(i, 1/A[i][i], A)

    #Upper diagonal inverse matrix
    return np.hsplit(A,2)[1]

In [11]:
# Prubea del código anterior
A = np.array([[1, 2, 3], [4, 0, 1], [7, 0, 9]], dtype=float)
print(A)
print('\n')
print(inverse_Gaussian_Elimination(A))
print('\n')
print(np.linalg.inv(A))

[[1. 2. 3.]
 [4. 0. 1.]
 [7. 0. 9.]]


[[ 0.          0.31034483 -0.03448276]
 [ 0.5         0.20689655 -0.18965517]
 [ 0.         -0.24137931  0.13793103]]


[[ 0.          0.31034483 -0.03448276]
 [ 0.5         0.20689655 -0.18965517]
 [-0.         -0.24137931  0.13793103]]
