## Unidad 3:

### Álgebra Lineal




**1** Haga una rutina que encuentre la inversa de una matriz por medio de la adjunta y luego encuentre la solución de las matrices $M_1$ y $M_2$.

**Nota** recuerde que la solucion de un sistema con el determinante se puede escribir como:
$$A^{-1}=\frac{1}{\det(A)} \cdot (\text{Adj}(A))^T $$
Por lo que deberá crear una función que encuentre la $(\text{Adj}(A))^T$

**Matrices de prueba**

$$M_1= \begin{bmatrix}
2 & 1 & 3 &|+ 3 \\
4 & -1 & 3 &|-4 \\
-1 & 5 & 5 &|+ 9
\end{bmatrix}$$

$$ M_2=\begin{bmatrix}
3 & 1 & 3 & -4 &|1 \\
6 & 4 & 8 & -10 &|5 \\
3 & 2 & 5 & -1 &|6 \\
-9 & 5 & -2 & -4& |2
\end{bmatrix} $$

Por definición $A^{-1}=\frac{1}{\det(A)} \cdot \text{Adj}(A)$ y no como realmente se había planteado.

In [43]:
import numpy as np

def dete(A):
    if len(A)!=len(A[0]):
        raise ValueError("La matriz debe ser cuadrada")
    det=0
    if len(A)==1:
        det=A[0]
    elif len(A)==2:
        det=A[0][0]*A[1][1]-A[1][0]*A[0][1]
    else:
        B=np.delete(A,0,axis=1)
        for j in range(len(A)):
            C=np.delete(B,j,axis=0)
            det+=A[j][0]*(-1)**(j)*dete(C)
    return det

def adjunta(A):
    A = np.copy(A)
    n = len(A) # Número de filas de la matriz
    if n != len(A[0]):
        raise ValueError("La matriz debe ser cuadrada")
    
    adjunta = np.zeros((n, n)) # Matriz adjunta de ceros para rellenar
    for i in range(n):
        for j in range(n):
            matriz_definicion = np.delete(np.delete(A, j, 0), i, 1) # Matriz sin la fila i y la columna j
            adjunta[i, j] = ((-1) ** (i + j)) * dete(matriz_definicion) # Definición de la adjunta
    return adjunta

In [44]:
M1 = np.array([[2, 1, 3],
               [4, -1, 3],
               [-1, 5, 5]])

M2 = np.array([[3, 1, 3, -4],
               [6, 4, 8, -10],
               [3, 2, 5, -1],
               [-9, 5, -2, -4]])

M1_inversa = adjunta(M1) / dete(M1)
M2_inversa = adjunta(M2) / dete(M2)

# Resultados con el código hecho
print("Inversa de M1 código:")
print(M1_inversa)
print('\n')
print("Inversa de M2 código:")
print(M2_inversa)
print('\n')

# Comprobación con numpy
print("Inversa de M1 numpy:")
print(np.linalg.inv(M1))
print('\n')
print("Inversa de M2 numpy:")
print(np.linalg.inv(M2))

Inversa de M1 código:
[[ 3.33333333 -1.66666667 -1.        ]
 [ 3.83333333 -2.16666667 -1.        ]
 [-3.16666667  1.83333333  1.        ]]


Inversa de M2 código:
[[ -9.41666667   4.29166667  -1.58333333  -0.91666667]
 [-14.75         6.625       -2.25        -1.25      ]
 [ 11.          -5.           2.           1.        ]
 [ -2.75         1.125       -0.25        -0.25      ]]


Inversa de M1 numpy:
[[ 3.33333333 -1.66666667 -1.        ]
 [ 3.83333333 -2.16666667 -1.        ]
 [-3.16666667  1.83333333  1.        ]]


Inversa de M2 numpy:
[[ -9.41666667   4.29166667  -1.58333333  -0.91666667]
 [-14.75         6.625       -2.25        -1.25      ]
 [ 11.          -5.           2.           1.        ]
 [ -2.75         1.125       -0.25        -0.25      ]]


**2** Las llamadas matrices de Pauli, están dadas por:


$$
σ_x={\begin{pmatrix}0&1\\1&0\end{pmatrix}},
$$

$$
σ_y={\begin{pmatrix}0&-i\\i&0\end{pmatrix}},
$$

$$
σ_z={\begin{pmatrix}1&0\\0&-1\end{pmatrix}},
$$

**A** Encuentre que $[σ_i,σ_j]\neq 0$ con $i,j= x,y, z$

**B** demuestre que ${σ_i}⁺={σ_i^*}^T=\sigma_i$ lo que significa que sus autovalores son reales.

**Nota** $[A,B]=AB-BA$


In [45]:
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

**3** Repita el ejercicio anterior usando sympy, encuentre que en efecto sus autovalores son reales.

**4.** Considere el código de eliminación gaussiana de clase, Modifíquelo para encontrar el determinante de una matriz general.

In [46]:
# Función para multiplicar una fila por un escalar
def row_lamb(i, lamb, A):
    M = np.copy(A)
    M[[i]] *= lamb
    return M

# Función para sumar una fila multiplicada por un escalar a otra fila
def row_comb(i, j, lamb, A):
    M = np.copy(A)
    M[[i]] += lamb * M[[j]]
    return M

# Función para intercambiar dos filas
def row_swap(i, j, A):
    M = np.copy(A)
    M[[i, j]] = M[[j, i]]
    return M

def determinante_matrz_eliminacion_g(A0):
    if A0.shape[0] != A0.shape[1]:
        raise ValueError('La matriz no es cuadrada')
    # Hacemos una copia local de la matriz
    A = np.copy(A0)
    n = len(A)
    b = np.full(n, 0) # Definimos el vector de ceros para la reducción
    A0 = np.column_stack((A, b)) # Matriz aumentada
    det_signo = 1 # Signo del determinante, el cual cambiará al hacer operaciones de intercambio de filas

    for i in range( 0, n ): # Iteración sobre las filas
        for j in range( i, n ): 
            if A[j,i] != 0:
                # Coeficiente de normalización
                Norm = 1.0*A[j,i]
                break

        # Operación de intercambio para poner el coeficiente no nulo en la i-ésima fila
        if i != j: # Si la fila con el coeficiente no nulo no es la i-ésima
            A = row_swap( i, j, A )
            det_signo *= -1 # Cambio de signo en el determinante

        # Eliminación el coeficiente asociado a la i-ésima variable
        for j in range( i+1, n ):
            A = row_comb( j, i, -A[j,i]/Norm, A )

    A_triang_sup = row_lamb( n-1, 1.0/A[n-1,n-1], A ) # Normalización de la variable n-ésima
    det = A_triang_sup.diagonal().prod() * det_signo # Determinante de la matriz como productoria de los elementos de la diagonal principal y signo

    return A_triang_sup, det

In [47]:
# Prueba del anterior código
A = np.array([[1, 0, 1], [1, 2, 4], [0, 1, 3]], dtype=float)
A_triang_sup, determinante = determinante_matrz_eliminacion_g(A)
print(f'Matriz original:\n{A}\n')
print(f'La matriz escalonada es:\n{A_triang_sup}\n y el determinante es: {determinante}')

Matriz original:
[[1. 0. 1.]
 [1. 2. 4.]
 [0. 1. 3.]]

La matriz escalonada es:
[[1. 0. 1.]
 [0. 2. 3.]
 [0. 0. 1.]]
 y el determinante es: 2.0


In [48]:
np.linalg.det(A) # Determinante calculado con numpy

2.9999999999999996

**5.** Considere el código de eliminación gaussiana de clase, Modifíquelo para encontrar la factorización PLU de una matriz general, tenga en cuenta que el código ya entrega la matriz U y solo es necesario crear L con las operaciones realizadas.

In [49]:
import numpy as np

def row_lamb(i, lamb, A):
    """Multiplica la fila i por un factor lambda en la matriz A."""
    A[i] *= lamb
    return A

def row_comb(i, j, lamb, A):
    """Combina la fila i con la fila j multiplicada por un factor lambda en la matriz A."""
    A[i] -= lamb * A[j]
    return A

def row_swap(i, j, A):
    """Intercambia las filas i y j de la matriz A."""
    A[[i, j]] = A[[j, i]]
    return A

def Gaussian_Elimination_LU(A0):
    # Making local copy of matrix
    A = np.copy(A0)
    # Detecting size of matrix
    n = len(A)
    # Initialize L as an identity matrix
    L = np.eye(n)

    # Sweeping all the columns in order to eliminate coefficients of the i-th variable
    for i in range(0, n):
        # Find index of maximum element in column i
        max_index = np.abs(A[i:, i]).argmax() + i

        # Swap rows i and max_index
        A[[i, max_index]] = A[[max_index, i]]
        L[[i, max_index]] = L[[max_index, i]]

        # Normalization coefficient
        Norm = 1.0 * A[i, i]

        # Eliminating the coefficient associated to the i-th variable
        for j in range(i + 1, n):
            factor = A[j, i] / Norm
            A[j] -= factor * A[i]
            # Store the multiplier in L
            L[j, i] = factor

    # The LU decomposition is now (L, A)
    return (L, A)

Comprobación y solución:

In [50]:
M2 = np.array([[2.,1.,3],[-1.,2,-1],[3,1,1]], dtype=float)

In [51]:
print('Matrices LU con el código proporcionado')
triangular_sup_codigo = Gaussian_Elimination_LU(M2)[1]
triangular_inf_codigo = Gaussian_Elimination_LU(M2)[0]
print(f'Matriz triangular superior: \n{triangular_sup_codigo}\n')
print(f'Matriz triangular inferior: \n{triangular_inf_codigo}')

Matrices LU con el código proporcionado
Matriz triangular superior: 
[[ 3.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  2.33333333e+00 -6.66666667e-01]
 [ 0.00000000e+00 -5.55111512e-17  2.42857143e+00]]

Matriz triangular inferior: 
[[ 0.          0.          1.        ]
 [-0.33333333  1.          0.        ]
 [ 0.66666667  0.14285714  0.        ]]


In [52]:
import scipy.linalg as LA
print('Matrices LU con scipy')
triangular_inferior = LA.lu(M2)[1:3][0]
triangular_superior = LA.lu(M2)[1:3][1]
print(f'Matriz triangular superior: \n{triangular_superior}')
print(f'Matriz triangular inferior: \n{triangular_inferior}\n')

Matrices LU con scipy
Matriz triangular superior: 
[[ 3.          1.          1.        ]
 [ 0.          2.33333333 -0.66666667]
 [ 0.          0.          2.42857143]]
Matriz triangular inferior: 
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [ 0.66666667  0.14285714  1.        ]]

