## Unidad 3:

### Álgebra Lineal




**1** Haga una rutina que encuentre la inversa de una matriz por medio de la adjunta y luego encuentre la solución de las matrices $M_1$ y $M_2$.

**Nota** recuerde que la solucion de un sistema con el determinante se puede escribir como:
$$A^{-1}=\frac{1}{\det(A)} \cdot \text{Adj}(A^T) $$
Por lo que deberá crear una función que encuentre la $\text{Adj}(A)^T$

**Matrices de prueba**

$$M_1= \begin{bmatrix}
2 & 1 & 3 &|+ 3 \\
4 & -1 & 3 &|-4 \\
-1 & 5 & 5 &|+ 9
\end{bmatrix}$$

$$ M_2=\begin{bmatrix}
3 & 1 & 3 & -4 &|1 \\
6 & 4 & 8 & -10 &|5 \\
3 & 2 & 5 & -1 &|6 \\
-9 & 5 & -2 & -4& |2
\end{bmatrix} $$

In [1]:
import numpy as np

**2** Las llamadas matrices de Pauli, están dadas por:


$$
σ_x={\begin{pmatrix}0&1\\1&0\end{pmatrix}},
$$

$$
σ_y={\begin{pmatrix}0&-i\\i&0\end{pmatrix}},
$$

$$
σ_z={\begin{pmatrix}1&0\\0&-1\end{pmatrix}},
$$

**A** Encuentre que $[σ_i,σ_j]\neq 0$ con $i,j= x,y, z$

**B** demuestre que ${σ_i}⁺={σ_i^*}^T=\sigma_i$ lo que significa que sus autovalores son reales.

**Nota** $[A,B]=AB-BA$


**3** Repita el ejercicio anterior usando sympy, encuentre que en efecto sus autovalores son reales.

**4.** Considere el código de eliminación gaussiana de clase, Modifíquelo para encontrar el determinante de una matriz general.

In [2]:
# Función para multiplicar una fila por un escalar
def row_lamb(i, lamb, A):
    M = np.copy(A)
    M[[i]] *= lamb
    return M

# Función para sumar una fila multiplicada por un escalar a otra fila
def row_comb(i, j, lamb, A):
    M = np.copy(A)
    M[[i]] += lamb * M[[j]]
    return M

# Función para intercambiar dos filas
def row_swap(i, j, A):
    M = np.copy(A)
    M[[i, j]] = M[[j, i]]
    return M

def determinante_matrz_eliminacion_g(A0):
    if A0.shape[0] != A0.shape[1]:
        raise ValueError('La matriz no es cuadrada')
    # Hacemos una copia local de la matriz
    A = np.copy(A0)
    n = len(A)
    b = np.full(n, 0) # Definimos el vector de ceros para la reducción
    A0 = np.column_stack((A, b)) # Matriz aumentada
    det_signo = 1 # Signo del determinante, el cual cambiará al hacer operaciones de intercambio de filas

    for i in range( 0, n ): # Iteración sobre las filas
        for j in range( i, n ): 
            if A[j,i] != 0:
                # Coeficiente de normalización
                Norm = 1.0*A[j,i]
                break

        # Operación de intercambio para poner el coeficiente no nulo en la i-ésima fila
        if i != j: # Si la fila con el coeficiente no nulo no es la i-ésima
            A = row_swap( i, j, A )
            det_signo *= -1 # Cambio de signo en el determinante

        # Eliminación el coeficiente asociado a la i-ésima variable
        for j in range( i+1, n ):
            A = row_comb( j, i, -A[j,i]/Norm, A )

    A_triang_sup = row_lamb( n-1, 1.0/A[n-1,n-1], A ) # Normalización de la variable n-ésima
    det = A_triang_sup.diagonal().prod() * det_signo # Determinante de la matriz como productoria de los elementos de la diagonal principal y signo

    return A_triang_sup, det

In [6]:
# Prueba del anterior código
A = np.array([[1, 0, 1], [1, 2, 4], [0, 1, 3]], dtype=float)
A_triang_sup, determinante = determinante_matrz_eliminacion_g(A)
print(f'Matriz original:\n{A}\n')
print(f'La matriz escalonada es:\n{A_triang_sup}\n y el determinante es: {determinante}')

Matriz original:
[[1. 0. 1.]
 [1. 2. 4.]
 [0. 1. 3.]]

La matriz escalonada es:
[[1. 0. 1.]
 [0. 2. 3.]
 [0. 0. 1.]]
 y el determinante es: 2.0


In [4]:
np.linalg.det(A) # Determinante calculado con numpy

32.0

**5.** Considere el código de eliminación gaussiana de clase, Modifíquelo para encontrar la factorización PLU de una matriz general, tenga en cuenta que el código ya entrega la matriz U y solo es necesario crear L con las operaciones realizadas.