<div align="left">
<img src="https://www.udea.edu.co/wps/wcm/connect/udea/99fc43e7-7a64-45bd-97fc-96639b70813d/logosimbolo-vertical.png?MOD=AJPERES&CVID=ljeLvHr" width="100" height="130" align="left" style="margin-right: 50px">
</div>

# Computational Methods workshops

Workshop 06

<div align="right" style="width: 99.5%;">
Estiven Castrillon
</div>

<div style="width: 99.5%; border-bottom: 3px solid white;"></div>

## Unidad 3:

### Álgebra Lineal




**1** Haga una rutina que encuentre la inversa de una matriz por medio de la adjunta y luego encuentre la solución de las matrices $M_1$ y $M_2$.

**Nota** recuerde que la solucion de un sistema con el determinante se puede escribir como:
$$A^{-1}=\frac{1}{\det(A)} \cdot (\text{Adj}(A))^T $$
Por lo que deberá crear una función que encuentre la $(\text{Adj}(A))^T$

**Matrices de prueba**

$$M_1= \begin{bmatrix}
2 & 1 & 3 &|+ 3 \\
4 & -1 & 3 &|-4 \\
-1 & 5 & 5 &|+ 9
\end{bmatrix}$$

$$ M_2=\begin{bmatrix}
3 & 1 & 3 & -4 &|1 \\
6 & 4 & 8 & -10 &|5 \\
3 & 2 & 5 & -1 &|6 \\
-9 & 5 & -2 & -4& |2
\end{bmatrix} $$

Por definición $A^{-1}=\frac{1}{\det(A)} \cdot \text{Adj}(A)$ y no como realmente se había planteado.

In [16]:
import numpy as np

In [17]:
# Código determinante de clase
def dete(A):
    if len(A)!=len(A[0]):
        raise ValueError("La matriz debe ser cuadrada")
    det=0
    if len(A)==1:
        det=A[0]
    elif len(A)==2:
        det=A[0][0]*A[1][1]-A[1][0]*A[0][1]
    else:
        B=np.delete(A,0,axis=1)
        for j in range(len(A)):
            C=np.delete(B,j,axis=0)
            det+=A[j][0]*(-1)**(j)*dete(C)
    return det

def adjunta(A):
    A = np.copy(A)
    n = len(A) # Número de filas de la matriz
    if n != len(A[0]):
        raise ValueError("La matriz debe ser cuadrada")
    
    adjunta = np.zeros((n, n)) # Matriz adjunta de ceros para rellenar
    for i in range(n):
        for j in range(n):
            matriz_definicion = np.delete(np.delete(A, j, 0), i, 1) # Matriz sin la fila i y la columna j
            adjunta[i, j] = ((-1) ** (i + j)) * dete(matriz_definicion) # Definición de la adjunta
    return adjunta

In [18]:
M1 = np.array([[2, 1, 3],
               [4, -1, 3],
               [-1, 5, 5]])

M2 = np.array([[3, 1, 3, -4],
               [6, 4, 8, -10],
               [3, 2, 5, -1],
               [-9, 5, -2, -4]])

M1_inversa = adjunta(M1) / dete(M1)
M2_inversa = adjunta(M2) / dete(M2)

# Resultados con el código hecho
print("Inversa de M1 código:")
print(M1_inversa)
print('\n')
print("Inversa de M2 código:")
print(M2_inversa)
print('\n')

# Comprobación con numpy
print("Inversa de M1 numpy:")
print(np.linalg.inv(M1))
print('\n')
print("Inversa de M2 numpy:")
print(np.linalg.inv(M2))

Inversa de M1 código:
[[ 3.33333333 -1.66666667 -1.        ]
 [ 3.83333333 -2.16666667 -1.        ]
 [-3.16666667  1.83333333  1.        ]]


Inversa de M2 código:
[[ -9.41666667   4.29166667  -1.58333333  -0.91666667]
 [-14.75         6.625       -2.25        -1.25      ]
 [ 11.          -5.           2.           1.        ]
 [ -2.75         1.125       -0.25        -0.25      ]]


Inversa de M1 numpy:
[[ 3.33333333 -1.66666667 -1.        ]
 [ 3.83333333 -2.16666667 -1.        ]
 [-3.16666667  1.83333333  1.        ]]


Inversa de M2 numpy:
[[ -9.41666667   4.29166667  -1.58333333  -0.91666667]
 [-14.75         6.625       -2.25        -1.25      ]
 [ 11.          -5.           2.           1.        ]
 [ -2.75         1.125       -0.25        -0.25      ]]


Tenemos un sistema $Ax=b$ donde $A$ es conocida y también su inversa, entonces para encontrar el vector $x$, hacemos lo siguiente $x = b \cdot A^{-1}$

In [19]:
b1 = np.array([3, -4, 9])
b2 = np.array([1, 5, 6, 2])
solucion_M1 = np.dot(M1_inversa, b1)
solucion_M2 = np.dot(M2_inversa, b2)

print('Soluciones a los sistemas dados:')
print("Solución de M1:")
print(solucion_M1)
print('\n')
print("Solución de M2:")
print(solucion_M2)

Soluciones a los sistemas dados:
Solución de M1:
[ 7.66666667 11.16666667 -7.83333333]


Solución de M2:
[0.70833333 2.375      0.         0.875     ]


**2** Las llamadas matrices de Pauli, están dadas por:


$$
σ_x={\begin{pmatrix}0&1\\1&0\end{pmatrix}},
$$

$$
σ_y={\begin{pmatrix}0&-i\\i&0\end{pmatrix}},
$$

$$
σ_z={\begin{pmatrix}1&0\\0&-1\end{pmatrix}},
$$

**A** Encuentre que $[σ_i,σ_j]\neq 0$ con $i,j= x,y, z$

**B** demuestre que ${σ_i}⁺={σ_i^*}^T=\sigma_i$ lo que significa que sus autovalores son reales.

**Nota** $[A,B]=AB-BA$


Nota: en el próxima código $\sigma_0 = \sigma_x$, $\sigma_1 = \sigma_y$ y $\sigma_2 = \sigma_z$

In [20]:
# Definición de las matrices de Pauli
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

# Lista de las matrices de Pauli
sigmas = [sigma_x, sigma_y, sigma_z]

# A) Viendo que las matrices multiplicadas son diferentes de cero
print('Viendo que las matrices multiplicadas son diferentes de cero:')
for i in range(3): # Recorriendo las matrices
    for j in range(i+1, 3): # Recorriendo las matrices restantes para hacer la multiplicación de dos en dos
        dos_en_dos = np.dot(sigmas[i], sigmas[j]) - np.dot(sigmas[j], sigmas[i]) # AB - BA
        print(f"[σ_{i}, σ_{j}] = \n{dos_en_dos}\n")

# B) Verificación de que las matrices son reales
print('Verificando que las matrices son reales:')
for i, sigma in enumerate(sigmas):
    print('Hi')
    print(f"sigma_{i}⁺ = σ_{i}^*^T = \n{np.conj(abs(sigma)).T}\n")

Viendo que las matrices multiplicadas son diferentes de cero:
[σ_0, σ_1] = 
[[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]

[σ_0, σ_2] = 
[[ 0 -2]
 [ 2  0]]

[σ_1, σ_2] = 
[[0.+0.j 0.+2.j]
 [0.+2.j 0.+0.j]]

Verificando que las matrices son reales:
Hi
sigma_0⁺ = σ_0^*^T = 
[[0 1]
 [1 0]]

Hi
sigma_1⁺ = σ_1^*^T = 
[[0. 1.]
 [1. 0.]]

Hi
sigma_2⁺ = σ_2^*^T = 
[[1 0]
 [0 1]]



**3** Repita el ejercicio anterior usando sympy, encuentre que en efecto sus autovalores son reales.

En efecto, los autovalores de las matrices son reales

In [21]:
from sympy import Matrix, I

sigma_x_sympy = Matrix([[0, 1], [1, 0]])
sigma_y_sympy = Matrix([[0, -I], [I, 0]])
sigma_z_sympy = Matrix([[1, 0], [0, -1]])

# Autovalores para cada matriz de Pauli
eigenvals_x = sigma_x_sympy.eigenvals()
eigenvals_y = sigma_y_sympy.eigenvals()
eigenvals_z = sigma_z_sympy.eigenvals()

print("Autovalores de sigma_x:", eigenvals_x)
print("Autovalores de sigma_y:", eigenvals_y)
print("Autovalores de sigma_z:", eigenvals_z)

Autovalores de sigma_x: {-1: 1, 1: 1}
Autovalores de sigma_y: {-1: 1, 1: 1}
Autovalores de sigma_z: {1: 1, -1: 1}


**4.** Considere el código de eliminación gaussiana de clase, Modifíquelo para encontrar el determinante de una matriz general.

In [22]:
# Función para multiplicar una fila por un escalar
def row_lamb(i, lamb, A):
    M = np.copy(A)
    M[[i]] *= lamb
    return M

# Función para sumar una fila multiplicada por un escalar a otra fila
def row_comb(i, j, lamb, A):
    M = np.copy(A)
    M[[i]] += lamb * M[[j]]
    return M

# Función para intercambiar dos filas
def row_swap(i, j, A):
    M = np.copy(A)
    M[[i, j]] = M[[j, i]]
    return M

def determinante_matriz_eliminacion_g(A0):
    if A0.shape[0] != A0.shape[1]:
        raise ValueError('La matriz no es cuadrada')
    A = np.copy(A0)  # Copia local de la matriz
    n = len(A)
    det_signo = 1 # Signo del determinante, el cual cambiará al hacer operaciones de intercambio de filas

    for i in range( 0, n ): # Iteración sobre las filas
        for j in range( i, n ): 
            if A[j,i] != 0:
                Norm = 1.0*A[j,i] # Coeficiente de normalización
                break

        # Operación de intercambio para poner el coeficiente no nulo en la i-ésima fila
        if i != j: # Si la fila con el coeficiente no nulo no es la i-ésima
            A = row_swap( i, j, A )
            det_signo *= -1 # Cambio de signo en el determinante

        # Eliminación el coeficiente asociado a la i-ésima variable
        for j in range( i+1, n ):
            A = row_comb( j, i, -A[j,i]/Norm, A )

    det = A.diagonal().prod() * det_signo # Determinante de la matriz como productoria de los elementos de la diagonal principal y signo

    return A, det

In [23]:
# Prueba del anterior código
A = np.array([[1, 0, 1], [1, 2, 4], [0, 1, 3]], dtype=float)
A_triang_sup, determinante = determinante_matriz_eliminacion_g(A)
print(f'Matriz original:\n{A}\n')
print(f'La matriz escalonada es:\n{A_triang_sup}\n y el determinante es: {determinante}')
print(f'Comprobación con numpy: {np.linalg.det(A).round(1)}')

Matriz original:
[[1. 0. 1.]
 [1. 2. 4.]
 [0. 1. 3.]]

La matriz escalonada es:
[[1.  0.  1. ]
 [0.  2.  3. ]
 [0.  0.  1.5]]
 y el determinante es: 3.0
Comprobación con numpy: 3.0


**5.** Considere el código de eliminación gaussiana de clase, Modifíquelo para encontrar la factorización PLU de una matriz general, tenga en cuenta que el código ya entrega la matriz U y solo es necesario crear L con las operaciones realizadas.

In [24]:
def PLU_Decomposition(A0):
    A = np.copy(A0)
    n = len(A) 
    L = np.eye(n) # L como la matriz identidad

    for i in range(0, n):
        for j in range(i, n):
            if A[j, i] != 0:
                Norm = 1.0 * A[j, i]
                break

        A = row_swap(i, j, A)

        for j in range(i + 1, n):
            factor = A[j, i] / Norm # multiplicador que se utiliza para eliminar los coeficientes de la matriz original durante el proceso de eliminación gaussiana
            A = row_comb(j, i, -factor, A)
            L[j, i] = factor  # Aquí se guarda el factor en la matriz L, es decir, la matriz triangular inferior

    # Matriz triangular superior U
    U = np.copy(A)

    return L, U

Comprobación y solución:

In [25]:
M2 = np.array([[2.,1.,3],[-1.,2,-1],[3,1,1]])

In [26]:
print('Matrices LU con el código proporcionado')
triangular_sup_codigo = PLU_Decomposition(M2)[1]
triangular_inf_codigo = PLU_Decomposition(M2)[0]
print(f'Matriz triangular inferior: \n{triangular_inf_codigo}')
print(f'Matriz triangular superior: \n{triangular_sup_codigo}\n')

Matrices LU con el código proporcionado
Matriz triangular inferior: 
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 1.5 -0.2  1. ]]
Matriz triangular superior: 
[[ 2.   1.   3. ]
 [ 0.   2.5  0.5]
 [ 0.   0.  -3.4]]



In [27]:
import scipy.linalg as LA
print('Matrices LU con scipy')
triangular_superior = LA.lu(M2)[1:3][1]
triangular_inferior = LA.lu(M2)[1:3][0]
print(f'Matriz triangular inferior: \n{triangular_inferior}\n')
print(f'Matriz triangular superior: \n{triangular_superior}')

Matrices LU con scipy
Matriz triangular inferior: 
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [ 0.66666667  0.14285714  1.        ]]

Matriz triangular superior: 
[[ 3.          1.          1.        ]
 [ 0.          2.33333333 -0.66666667]
 [ 0.          0.          2.42857143]]
